BoxLayout:
    orientation: 'vertical'
    BoxLayout:
        orientation: 'horizontal'
        TextInput:
            text: ''

        BoxLayout:
            orientation: 'vertical'
            size_hint_x = 0.2
            Button:
                text: 'Up'

            Button:
                text: 'Down'


    Button:
        text: 'Convert miles to km'

    Label:
         id: output_label


